//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using Smark.Data.Mappings;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;


namespace NorthWind.DBModule {
    
    
    /// <summary>
    /// Smark.Data Generator Copyright © FanJianHan 2010-2012
    /// website:http://www.ikende.com
    /// </summary>
    [Serializable()]
    [Table("Orders")]
    public partial class Order : Smark.Data.Mappings.DataObject, IOrder {
        
        private int mOrderID;
        
        /// <summary>
        /// System.Int32
        /// </summary>
        public static Smark.Data.FieldInfo orderID = new Smark.Data.FieldInfo("Orders", "OrderID");
        
        private string mCustomerID;
        
        /// <summary>
        /// System.String
        /// </summary>
        public static Smark.Data.FieldInfo customerID = new Smark.Data.FieldInfo("Orders", "CustomerID");
        
        private int mEmployeeID;
        
        /// <summary>
        /// System.Int32
        /// </summary>
        public static Smark.Data.FieldInfo employeeID = new Smark.Data.FieldInfo("Orders", "EmployeeID");
        
        private DateTime mOrderDate;
        
        /// <summary>
        /// DateTime
        /// </summary>
        public static Smark.Data.FieldInfo orderDate = new Smark.Data.FieldInfo("Orders", "OrderDate");
        
        private DateTime mRequiredDate;
        
        /// <summary>
        /// DateTime
        /// </summary>
        public static Smark.Data.FieldInfo requiredDate = new Smark.Data.FieldInfo("Orders", "RequiredDate");
        
        private DateTime mShippedDate;
        
        /// <summary>
        /// DateTime
        /// </summary>
        public static Smark.Data.FieldInfo shippedDate = new Smark.Data.FieldInfo("Orders", "ShippedDate");
        
        private long mShipVia;
        
        /// <summary>
        /// System.Int64
        /// </summary>
        public static Smark.Data.FieldInfo shipVia = new Smark.Data.FieldInfo("Orders", "ShipVia");
        
        private decimal mFreight;
        
        /// <summary>
        /// System.Decimal
        /// </summary>
        public static Smark.Data.FieldInfo freight = new Smark.Data.FieldInfo("Orders", "Freight");
        
        private string mShipName;
        
        /// <summary>
        /// System.String
        /// </summary>
        public static Smark.Data.FieldInfo shipName = new Smark.Data.FieldInfo("Orders", "ShipName");
        
        private string mShipAddress;
        
        /// <summary>
        /// System.String
        /// </summary>
        public static Smark.Data.FieldInfo shipAddress = new Smark.Data.FieldInfo("Orders", "ShipAddress");
        
        private string mShipCity;
        
        /// <summary>
        /// System.String
        /// </summary>
        public static Smark.Data.FieldInfo shipCity = new Smark.Data.FieldInfo("Orders", "ShipCity");
        
        private string mShipRegion;
        
        /// <summary>
        /// System.String
        /// </summary>
        public static Smark.Data.FieldInfo shipRegion = new Smark.Data.FieldInfo("Orders", "ShipRegion");
        
        private string mShipPostalCode;
        
        /// <summary>
        /// System.String
        /// </summary>
        public static Smark.Data.FieldInfo shipPostalCode = new Smark.Data.FieldInfo("Orders", "ShipPostalCode");
        
        private string mShipCountry;
        
        /// <summary>
        /// System.String
        /// </summary>
        public static Smark.Data.FieldInfo shipCountry = new Smark.Data.FieldInfo("Orders", "ShipCountry");
        
        [ID()]
        [IDENTITY()]
        public virtual int OrderID {
            get {
                return this.mOrderID;
            }
            set {
                this.mOrderID = value;
                this.EntityState.FieldChange("OrderID");
            }
        }
        
        [Column()]
        public virtual string CustomerID {
            get {
                return this.mCustomerID;
            }
            set {
                this.mCustomerID = value;
                this.EntityState.FieldChange("CustomerID");
            }
        }
        
        [Column()]
        public virtual int EmployeeID {
            get {
                return this.mEmployeeID;
            }
            set {
                this.mEmployeeID = value;
                this.EntityState.FieldChange("EmployeeID");
            }
        }
        
        [Column()]
        public virtual DateTime OrderDate {
            get {
                return this.mOrderDate;
            }
            set {
                this.mOrderDate = value;
                this.EntityState.FieldChange("OrderDate");
            }
        }
        
        [Column()]
        public virtual DateTime RequiredDate {
            get {
                return this.mRequiredDate;
            }
            set {
                this.mRequiredDate = value;
                this.EntityState.FieldChange("RequiredDate");
            }
        }
        
        [Column()]
        public virtual DateTime ShippedDate {
            get {
                return this.mShippedDate;
            }
            set {
                this.mShippedDate = value;
                this.EntityState.FieldChange("ShippedDate");
            }
        }
        
        [Column()]
        public virtual long ShipVia {
            get {
                return this.mShipVia;
            }
            set {
                this.mShipVia = value;
                this.EntityState.FieldChange("ShipVia");
            }
        }
        
        [Column()]
        public virtual decimal Freight {
            get {
                return this.mFreight;
            }
            set {
                this.mFreight = value;
                this.EntityState.FieldChange("Freight");
            }
        }
        
        [Column()]
        public virtual string ShipName {
            get {
                return this.mShipName;
            }
            set {
                this.mShipName = value;
                this.EntityState.FieldChange("ShipName");
            }
        }
        
        [Column()]
        public virtual string ShipAddress {
            get {
                return this.mShipAddress;
            }
            set {
                this.mShipAddress = value;
                this.EntityState.FieldChange("ShipAddress");
            }
        }
        
        [Column()]
        public virtual string ShipCity {
            get {
                return this.mShipCity;
            }
            set {
                this.mShipCity = value;
                this.EntityState.FieldChange("ShipCity");
            }
        }
        
        [Column()]
        public virtual string ShipRegion {
            get {
                return this.mShipRegion;
            }
            set {
                this.mShipRegion = value;
                this.EntityState.FieldChange("ShipRegion");
            }
        }
        
        [Column()]
        public virtual string ShipPostalCode {
            get {
                return this.mShipPostalCode;
            }
            set {
                this.mShipPostalCode = value;
                this.EntityState.FieldChange("ShipPostalCode");
            }
        }
        
        [Column()]
        public virtual string ShipCountry {
            get {
                return this.mShipCountry;
            }
            set {
                this.mShipCountry = value;
                this.EntityState.FieldChange("ShipCountry");
            }
        }
    }
}
