//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using Smark.Data.Mappings;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;


namespace NorthWind.DBModule {
    
    
    /// <summary>
    /// Smark.Data Generator Copyright © FanJianHan 2010-2012
    /// website:http://www.ikende.com
    /// </summary>
    [Serializable()]
    [Table("Shippers")]
    public partial class Shipper : Smark.Data.Mappings.DataObject, IShipper {
        
        private int mShipperID;
        
        /// <summary>
        /// System.Int32
        /// </summary>
        public static Smark.Data.FieldInfo shipperID = new Smark.Data.FieldInfo("Shippers", "ShipperID");
        
        private string mCompanyName;
        
        /// <summary>
        /// System.String
        /// </summary>
        public static Smark.Data.FieldInfo companyName = new Smark.Data.FieldInfo("Shippers", "CompanyName");
        
        private string mPhone;
        
        /// <summary>
        /// System.String
        /// </summary>
        public static Smark.Data.FieldInfo phone = new Smark.Data.FieldInfo("Shippers", "Phone");
        
        [ID()]
        [IDENTITY()]
        public virtual int ShipperID {
            get {
                return this.mShipperID;
            }
            set {
                this.mShipperID = value;
                this.EntityState.FieldChange("ShipperID");
            }
        }
        
        [Column()]
        public virtual string CompanyName {
            get {
                return this.mCompanyName;
            }
            set {
                this.mCompanyName = value;
                this.EntityState.FieldChange("CompanyName");
            }
        }
        
        [Column()]
        public virtual string Phone {
            get {
                return this.mPhone;
            }
            set {
                this.mPhone = value;
                this.EntityState.FieldChange("Phone");
            }
        }
    }
}
